org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=serverdelight
mod_name=Farmer's Delight Add-on Server Delight
mod_license=MIT
mod_version=1.1
mod_group_id=com.maxwell.yamaokaya
mod_authors=maxwell, sharkinn
mod_description=This mod add some foods about
jei_version=15.20.0.105